---
exclude: '^(external|vendor)/'
repos:
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        entry: shfmt
        args: [-w, -i, "4"]
        language: system
        types: [shell]
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]

  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        args: [-conf, .yamlfmt.yaml]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
